# -*- coding: utf-8 -*-
"""DualPathCNN and Transformer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHJU7ytFgJPAHpjiLi8PB_xwKJep2qqP
"""

import torch
import torch.nn.functional as F
import torch.nn as cnn
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
from PIL import Image
from torchvision import datasets,transforms
from torchvision.utils import make_grid
import numpy as np
import pandas as pd
from tqdm import tqdm
from torchvision import models
import torch.optim as optim
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import roc_curve,auc
from sklearn.preprocessing import label_binarize
import seaborn as sns
import matplotlib.pyplot as plt
import os
from torch.utils.data import random_split

"""# 1. Locate the Dataset"""

from google.colab import drive
drive.mount('/content/drive')

train_folder ="/content/drive/MyDrive/Colab/Dataset/archive/train"
test_folder = '/content/drive/MyDrive/Colab/Dataset/archive/Test/cases'

print(os.listdir(train_folder))

"""# 2. Setup Device-Agnostic Code"""

device = "cuda" if torch.cuda.is_available() else "cpu"

#PREPROCESSING
class DualDataset(Dataset):
  def __init__(self,address):
    self.address = address
    self.samples = []
    self.label_map ={
        "Normal cases":0,
        "Bengin cases":1,
        "Malignant cases":2
    }

    for label_name in os.listdir(address):
        if label_name not in self.label_map:
           continue

        cls_folder = os.path.join(address,label_name)

        for img_name in os.listdir(cls_folder):
          img_path = os.path.join(cls_folder,img_name)
          self.samples.append((img_path,self.label_map[label_name]))
    norm = transforms.Normalize(mean=[0.485,0.456,0.406], std = [0.229,0.224,0.225])
    #Local features
    self.transform = transforms.Compose([
        transforms.Resize((224,224)),
        transforms.ToTensor(),norm ])
    #Global Features
    self.transform_global = transforms.Compose([
         transforms.Resize((128,128)),
         transforms.ToTensor(),norm ])
  def __getitem__(self, index):
      image_path,label = self.samples[index]

      local_image = self.transform(Image.open(image_path))
      global_image = self.transform_global(Image.open(image_path))
      return local_image,global_image,int(label)
  def __len__(self):
    return len(self.samples)

class TestDualDataset(Dataset):
    def __init__(self, address):
        self.address = address
        self.samples = []

        # Collect all images in the folder
        for img_name in os.listdir(address):
            if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
                img_path = os.path.join(address, img_name)
                self.samples.append(img_path)

        norm = transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])

        self.transform = transforms.Compose([
            transforms.Resize((224,224)),
            transforms.ToTensor(),
            norm
        ])

        self.transform_global = transforms.Compose([
            transforms.Resize((128,128)),
            transforms.ToTensor(),
            norm
        ])

    def __getitem__(self, index):
        image_path = self.samples[index]
        local_image = self.transform(Image.open(image_path).convert('RGB'))
        global_image = self.transform_global(Image.open(image_path).convert('RGB'))
        return local_image, global_image

    def __len__(self):
        return len(self.samples)

dataset = DualDataset(train_folder)

loader = DataLoader(dataset,batch_size=32,shuffle=True)
for local, global_,label in loader:
  print(local.shape)
  print(global_.shape)
  print(label)
  break

print("Train samples:", len(dataset))

"""# Converting Dataset into DataLoaders"""

full_dataset = DualDataset(train_folder)
train_size = int(0.8 * len(dataset))
val_size= len(full_dataset)-train_size
train_dataset, val_dataset = random_split(dataset, [train_size,val_size])

#Dataloaders
train_dataset = DualDataset(train_folder)
test_dataset = TestDualDataset(test_folder)

train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32, shuffle=False)
val_loader   = DataLoader(val_dataset, batch_size=32, shuffle=False)

print("Test samples:", len(test_dataset))
print("Test batches:", len(test_loader))
print(len(train_dataset))

"""# Define CNN model"""

#Define LocalCNN
class LocalCNN(cnn.Module):
  def __init__(self):
    super().__init__()
    backbone = models.resnet18(weights="IMAGENET1K_V1")
    self.features = cnn.Sequential(*list(backbone.children())[:-1])
    self.fc = cnn.Linear(512, 512)

  def forward(self, x):
      x = self.features(x)
      x = x.flatten(1)
      return self.fc(x)

#Define GlobalCNN
class GlobalCNN(cnn.Module):
  def __init__(self):
     super().__init__()
     backbone = models.resnet18(weights="IMAGENET1K_V1")
     self.features = cnn.Sequential(*list(backbone.children())[:-1])
     self.fc = cnn.Linear(512, 512)

  def forward(self, x):
        x = self.features(x)
        x = x.flatten(1)
        return self.fc(x)

#CHECKING The loop
if __name__ == "__main__":
    local = LocalCNN()
    global_ = GlobalCNN()

    # dummy batch
    x_local = torch.randn(4,3,224,224)
    x_global = torch.randn(4,3,128,128)

    lf = local(x_local)
    gf = global_(x_global)

    print("Local feature shape:", lf.shape)    # [4, 512]
    print("Global feature shape:", gf.shape)

"""# Build DualPath Transformer Model


"""

class DualPathTransformer(cnn.Module):
  def __init__(self,dim =512,heads =8,layers=2,classes=3):
    super().__init__()
    self.local = LocalCNN()
    self.global_ = GlobalCNN()


    self.proj = cnn.Linear(512,dim)
    self.cls = cnn.Parameter(torch.rand(1,1,dim))
    encoder_layer = cnn.TransformerEncoderLayer(
            d_model=dim,
            nhead=heads,
            batch_first=True
        )
    self.transformer = cnn.TransformerEncoder(encoder_layer, num_layers=layers)

        # Final classification head
    self.classifier = cnn.Linear(dim,classes)

  def forward(self, x_local, x_global):
    lf = self.local(x_local)    # (B,512)
    gf = self.global_(x_global) # (B,512)

    B = lf.size(0)

    lf = lf.unsqueeze(1)  # (B,1,512)
    gf = gf.unsqueeze(1)  # (B,1,512)

    x = torch.cat((lf, gf), dim=1)  # (B,2,512)
    x = self.proj(x)                # (B,2,dim)

    cls = self.cls.expand(B, -1, -1)
    x = torch.cat((cls, x), dim=1)  # (B,3,dim)

    x = self.transformer(x)
    cls_out = x[:, 0]

    return self.classifier(cls_out)

"""### DualPathTransformer Architecture

The `DualPathTransformer` model processes image data through two distinct pathways, one for local features and another for global features, before combining them using a Transformer Encoder for final classification.

Here's a breakdown of the architecture:

1.  **LocalCNN Branch (`LocalCNN`)**:
    *   **Input**: Takes local image patches (224x224 pixels).
    *   **Feature Extractor**: Utilizes a pre-trained ResNet18 (ImageNet weights) as its backbone, removing the final classification layer.
    *   **Output Layer**: A fully connected (FC) layer transforms the ResNet18 features into a 512-dimensional vector, representing local image features.

2.  **GlobalCNN Branch (`GlobalCNN`)**:
    *   **Input**: Takes global image context (128x128 pixels).
    *   **Feature Extractor**: Also uses a pre-trained ResNet18 (ImageNet weights) as its backbone, with the final classification layer removed.
    *   **Output Layer**: A fully connected (FC) layer transforms these features into a 512-dimensional vector, representing global image features.

3.  **Feature Combination and Projection**:
    *   The 512-dimensional feature vectors from both `LocalCNN` and `GlobalCNN` are independently projected to a `dim` (default 512) dimensional space using a linear layer (`self.proj`).
    *   A learnable classification token (`self.cls`) is prepended to these projected feature vectors.
    *   These three tokens (classification token, local feature token, global feature token) form the input sequence to the Transformer Encoder.

4.  **Transformer Encoder (`cnn.TransformerEncoder`)**:
    *   **Input**: A sequence of tokens (`[cls_token, local_feature_token, global_feature_token]`).
    *   **Processing**: Comprises multiple `TransformerEncoderLayer` modules (configured with `dim`, `heads`, and `layers`). These layers capture complex relationships and dependencies between the local and global features, as well as the classification token.

5.  **Classification Head**:
    *   **Input**: The output corresponding to the classification token from the Transformer Encoder.
    *   **Output Layer**: A final linear layer (`self.classifier`) maps the Transformer's output for the classification token to the number of output `classes` (e.g., 3 for Normal, Benign, Malignant).

**Overall Flow**:
Images are simultaneously processed by the local and global CNNs. Their extracted features are then combined with a classification token and fed into a Transformer Encoder. The Transformer learns to integrate these features, and the output of its classification token is used by a final linear layer to predict the class of the input image.
"""

#Instantiate Model
model =DualPathTransformer(dim=512,heads=8,layers=2,classes=3).to(device)

print(next(model.parameters()).device)

"""# Loss function and Optimizer"""

#Define Loss function and Optimizer
criterion = cnn.CrossEntropyLoss().to(device)
model = DualPathTransformer().to(device)
optimizer = optim.Adam(model.parameters(),lr=3e-4,weight_decay=1e-4)

print(criterion)

"""# Define Training Loop and Function"""

#Training Function
def train(model,train_loader,optimizer,criterion,device):
  model.train()
  current_loss = 0.0
  correct =0
  total = 0
  for local_img,global_img,labels in tqdm(train_loader):
    local_img = local_img.to(device)
    global_img = global_img.to(device)
    labels = labels.to(device).squeeze().long()

    optimizer.zero_grad()
    outputs = model(local_img,global_img)
    loss = criterion(outputs,labels)
    loss.backward()
    optimizer.step()

    current_loss += loss.item()*label.size(0)
    preds = outputs.argmax(dim=1)
    correct += (preds == labels).sum().item()
    total += labels.size(0)

  epoch_loss = current_loss / total
  epoch_acc = correct / total

  return epoch_loss, epoch_acc

def evaluate(model, loader, criterion, device):
    model.eval()  # set model to evaluation mode

    running_loss = 0.0
    all_preds = []
    all_labels = []



    with torch.no_grad():
        for local_img, global_img, labels in loader:
            # Move to device
            local_img = local_img.to(device)
            global_img = global_img.to(device)
            labels = labels.to(device)
            labels = labels.long()





            # Forward pass
            outputs = model(local_img, global_img)  # model should take both paths
            #print("outputs:", outputs.shape, outputs.dtype)
            #print("labels :", labels.shape, labels.dtype)
            #print("labels example:", labels[:5])
            loss = criterion(outputs, labels)

            running_loss += loss.item() * labels.size(0)  # sum of batch loss

            # Predictions
            preds = outputs.argmax(dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())


    # Compute average loss and accuracy
    avg_loss = running_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)

    return avg_loss, acc, all_labels, all_preds

evaluate(model,val_loader,criterion,device)

#Main Training Loop
num_epochs = 5
train_losses, val_losses = [], []
train_accs, val_accs = [], []

for epoch in range(num_epochs):
    train_loss, train_acc = train(
        model, train_loader, optimizer, criterion, device
    )

    val_loss, val_acc, y_true, y_pred = evaluate(
        model, val_loader, criterion, device
    )

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(f"Epoch [{epoch+1}/{num_epochs}]")
    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Val   Loss: {val_loss:.4f} | Val   Acc: {val_acc:.4f}")
    print("-" * 50)

print("Test samples:", len(DualDataset(test_folder)))
print("Test folder contents:", os.listdir(test_folder))

def predict(model, loader, device):
    model.eval()
    preds = []

    with torch.no_grad():
        for local_img, global_img in loader:
            local_img = local_img.to(device)
            global_img = global_img.to(device)

            outputs = model(local_img, global_img)
            predicted = torch.argmax(outputs, dim=1)
            preds.extend(predicted.cpu().numpy())

    return preds

pred = predict(
    model,
    test_loader,
    device
)
print(pred)

"""# Metrics for measurement"""

#Confusion Matrix
class_names = ["Normal", "Benign", "Malignant"]

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

precision = precision_score(y_true, y_pred, average="macro")
recall = recall_score(y_true, y_pred, average="macro")   # sensitivity
f1 = f1_score(y_true, y_pred, average="macro")

print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-score  : {f1:.4f}")

#Loss function
epochs = range(1, len(train_losses) + 1)

plt.figure(figsize=(6,4))
plt.plot(epochs, train_losses, label="Train Loss")
plt.plot(epochs, val_losses, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

#AUC
model.eval()
all_probs = []
all_labels = []

with torch.no_grad():
    for local_img, global_img, labels in val_loader:
        local_img = local_img.to(device)
        global_img = global_img.to(device)
        labels = labels.to(device)

        outputs = model(local_img, global_img)
        probs = F.softmax(outputs, dim=1)

        all_probs.append(probs.cpu().numpy())
        all_labels.append(labels.numpy())

y_prob = np.concatenate(all_probs)
y_true = np.concatenate(all_labels)

num_classes = 3
class_names = ["Normal", "Benign", "Malignant"]

y_true_bin = label_binarize(y_true, classes=[0,1,2])

plt.figure(figsize=(6,5))

for i in range(num_classes):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_prob[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{class_names[i]} (AUC = {roc_auc:.3f})")

plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-Class ROC Curve")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
plt.plot(epochs, train_accs, label="Train Accuracy")
plt.plot(epochs, val_accs, label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Model Convergence Behavior")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Validation error
val_errors = [1 - acc for acc in val_accs]

plt.figure(figsize=(6,4))
plt.plot(epochs, val_errors, color="red")
plt.xlabel("Epochs")
plt.ylabel("Validation Error")
plt.title("Validation Error Behavior")
plt.grid(True)
plt.tight_layout()
plt.show()



torch.save(model.state_dict(), "dual_path_transformer.pth")